// <auto-generated />
using System;
using HomeTask9.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeTask9.Migrations
{
    [DbContext(typeof(UserDBContext))]
    partial class UserDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeTask9.UserModels.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NameState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "NameState");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hans Christian Andersen",
                            NameState = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comic",
                            NameState = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Novel",
                            NameState = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bobby Lynn Maslen",
                            NameState = 0
                        });
                });

            modelBuilder.Entity("HomeTask9.UserModels.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("StoryId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 14,
                            AuthorId = 1,
                            FirstName = "Finn",
                            LastName = "Mertens",
                            StoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 2700,
                            AuthorId = 4,
                            FirstName = "Philip",
                            LastName = "Fry",
                            StoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            AuthorId = 3,
                            FirstName = "Anakin",
                            LastName = "Skywalker",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 4,
                            AuthorId = 2,
                            FirstName = "Varian",
                            LastName = "Wrynn",
                            StoryId = 3
                        });
                });

            modelBuilder.Entity("HomeTask9.UserModels.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Fairytail of the lost needle"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Clone Wars"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Cool story, Bob"
                        });
                });

            modelBuilder.Entity("HomeTask9.UserModels.Character", b =>
                {
                    b.HasOne("HomeTask9.UserModels.Author", "Authors")
                        .WithMany("Characters")
                        .HasForeignKey("AuthorId");

                    b.HasOne("HomeTask9.UserModels.Story", "Stories")
                        .WithMany("Characters")
                        .HasForeignKey("StoryId");

                    b.Navigation("Authors");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("HomeTask9.UserModels.Author", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("HomeTask9.UserModels.Story", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
